lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    resources "/follows", FollowController
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
   scope "/api/v1", MicroblogWeb do
     pipe_through :api

     resources "/likes", LikeController, except: [:new, :edit]
   end
end

lib/microblog/blog/post.ex
defmodule Microblog.Blog.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Blog.Post


  schema "posts" do
    field :body, :string
    field :title, :string
    belongs_to :user, Microblog.Accounts.User

    timestamps()
  end
 

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title, :body, :user_id])
    |> validate_required([:body])
    |> assoc_constraint(:user)
  end
end

lib/microblog_web/controllers/post_controller.ex
defmodule MicroblogWeb.PostController do
  use MicroblogWeb, :controller

  alias Microblog.Blog
  alias Microblog.Blog.Post

  def index(conn, _params) do
    changeset = Blog.change_post(%Post{})
    posts = Blog.list_posts() |> Microblog.Repo.preload([:user])
    render(conn, "index.html", posts: posts, changeset: changeset)
  end

  def index(conn, %{"user_id" => user_id}) do
    changeset = Blog.change_post(%Post{})
    posts = Blog.list_user_posts(user_id) |> Microblog.Repo.preload([:user])
    render(conn, "index.html", posts: posts, changeset: changeset)
  end

  def new(conn, _params) do
    changeset = Blog.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Blog.create_post(post_params) do
     {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: post_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Blog.get_post!(id) |> Microblog.Repo.preload([:user])
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    changeset = Blog.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Blog.get_post!(id)

    case Blog.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    {:ok, _post} = Blog.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: post_path(conn, :index))
  end
end

lib/microblog_web/views/post_view.ex
defmodule MicroblogWeb.PostView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/post/edit.html.eex
<h2>Edit Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

lib/microblog_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
 
 <p id="post-user"><%=  @current_user.email %></ip>

    <%= hidden_input f, :user_id, value: @current_user.id %>
  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control", id: "newTitle" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control", id: "newBody" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
   <%= submit "Submit", class: "btn btn-primary", id: "postSubmit" %>
  </div>
<% end %>

lib/microblog_web/templates/post/form2.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
 
  <p id="user-info" data-user_username= "<%= @current_user.username %>"><%=  @current_user.email  %></p>

    <%= hidden_input f, :user_id, value: @current_user.id %>
  <div class="form-group">
    <%= text_input f, :title, class: "form-control", id: "newTitle", placeholder: "Title" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= textarea f, :body, class: "form-control", id: "newBody", placeholder: "Body" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
   <%= submit "Post", class: "btn btn-dark btn-xs", id: "post-submit" %>
  </div>
<% end %>

lib/microblog_web/templates/post/index.html.eex
<br />
<br />
<%= if @current_user !== nil do %>
<div class="container-fluid" style="margin-left: 10%; margin-top: 3%;">
  <div class="col-md-12">
  <br />
  <div class = "row">
    <div id="np" class="col-md-9">
	<%= render "form2.html", Map.put(assigns, :action, post_path(@conn, :create)) %>
    </div>
  </div>
  <br />
  <br />
  <div id="posts" class="col-md-9">
      <%= for post <- @posts do %>
        <div class="row">
        <br />
        <div class="card border-secondary mb-3" style="margin: 0 auto; width: 40rem;">
           <div class="card-header">
	       <div class="col-md-12" style="margin: 0;">
		  <%= post.user.username %>
		  <%= if @current_user.id == post.user_id do %>
		  <div class="btns">               
		    <span style="margin-left: 40%;"><%= link "Edit", to: post_path(@conn, :edit, post), class: "btn btn-primary btn-xs" %></span>
        <span><%= link "Delete", to: post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>   
		  </div> 
        <% else %> 
		  <div>
		  <span style="left-margin: 40%;"><%= link "View to like", to: post_path(@conn, :show, post), class: "btn btn-warning btn-xs"%></span>
		  </div>
		  <% end %>	    
	       </div>
           </div>
           <div class="card-body">
             <h4 class="card-title"><%= post.title %></h4>
             <p class="card-text"><%= post.body %></p>
           </div>
         </div>
       </div>
    <% end %>
  </div>
 </div>
</div>
<% end %>

lib/microblog_web/templates/post/login.hmtl.eex
<%= if @current_user == nil do %>
<div class="container">
    <div class="row">
        <div class="col-md-6" style= "margin: 0 auto;">
          <img src="http://i149.photobucket.com/albums/s71/dylancolesss/Logomakr_1JQf3o_1.png" border="0" alt=" photo Logomakr_1JQf3o_1.png" style="width:100%; height:100%;"/>
      	</div>
    </div>
    <br />
    <br />
    <div class="row">
        <div class="col-md-5" style="margin: 0 auto; text-align: center;">
            <h1>New Account</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" style= "margin: 0 auto;">
          <%= form_for @conn, session_path(@conn, :login), 
			[as: "user", class: "form-inline w-75"], fn f -> %>
            <input type="text" placeholder="email" class="form-control" name="email">
            <input type="password" placeholder="password" class="form-control" name="password">
            <input type="submit" value="Login" class="btn btn-dark">
    	  <% end %>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6" style="margin: 0 auto;">
    		<span>
                <%= link "Sign Up", to: user_path(@conn, :new), class: "btn btn-dark" %>
            </span>
    	</div>
    </div>
</div>
<% end %>

lib/microblog_web/templates/post/new.html.eex
<h2>New Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :create)) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

lib/microblog_web/templates/post/show.html.eex
<h2>Show Post</h2>

<div class="container-fluid" style="margin-top: 5%;">
    <div class="col-md-12">
      <span><%= link "Back", to: post_path(@conn, :index) %></span>
      <br />
      <div class="card border-secondary mb-3">
        <div class="card-header">
          <div class="col-md-6" style="margin: 0;"> <%= @post.user.username %>
            <%= if @current_user.id == @post.user_id do %>
            <div>
                <span style="margin-left: 50%"><%= link "Edit", to: post_path(@conn, :edit, @post), class: "btn btn-primary btn-xs"%></span>
             </div>
             <% else %>
             <%= if Microblog.Liking.check_user(@current_user.id, @post.id) == nil do %>
            <div>
              <button id="like-button" class="btn btn-danger btn-xs" 
                  data-user-id="<%= @current_user.id %>">Like</button>
            </div>
            <% end %>
           <% end %>
           </div>
        </div>
        <div class="card-body">
          <h4 class="card-title"><%= @post.title %></h4>
          <p class="card-text"><%= @post.body%></p>
        </div>
          <ul class="list-group list-group-flush" id="likes" data-path="<%= like_path(@conn, :index) %>" 
                            data-post_id="<%= @post.id %>"> 
              &nbsp;
          </ul> 

          <script id="likes-template" type="text/x-handlebars-template">
                 <ul class="list-group list-group-flush">

                {{#each data}}
                 <li class="list-group-item">{{user_username}} liked this!</li>
                {{else}}
                  <li class="list-group-item">be the first!</li>
                {{/each}}
                </ul>
          </script>
    </div>
    </div>
</div>