lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    resources "/follows", FollowController
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
   scope "/api/v1", MicroblogWeb do
     pipe_through :api

     resources "/likes", LikeController, except: [:new, :edit]
   end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Microblog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>"
  </head>

  <body>
       <header> 
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
              <a class="navbar-brand" href="#">MIME</a>
                 <div class="collapse navbar-collapse" id="main-navbar">
                      <ul class="navbar-nav mr-auto">
                         <li class="nav-item">
                            <%= if @current_user do %>
                              <%= link "Profile", to: user_path(@conn, :show, @current_user.id), class: "nav-link"%>
                            <% end %> 
			 </li>
                         <li class="nav-item">
                            <%= link "Posts", to: post_path(@conn, :index), class: "nav-link"%>
                         </li>
			 <li class="nav-item">
			    <%= if @current_user do %>
			    <%= if @current_user.is_admin? do %>
			      <%= link "Users", to: user_path(@conn, :index), class: "nav-link" %>
			    <% end %>
			    <% end %>
			 </li>
                         <li class="nav-item">
                            <%= if @current_user do %>
                              <%= link "New Posts", to: post_path(@conn, :new), class: "btn btn-light btn-xs"%>
                         <% end %>
                         </li>
                     </ul>
               </div>

              <%= if @current_user do %>
                <span class="text-light">
                  <%= @current_user.username %> |
                     <%= link("logout", to: session_path(@conn, :logout), method: :delete) %>
                </span>
              <% end %>
        </nav>
      </header>

	<div class="container">
      <br />
      <%= if get_flash(@conn, :info) do %>
    	<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
    	<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

    <%= if @current_user == nil do %>
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-6" style= "margin: 0 auto;">
          <img src="http://i149.photobucket.com/albums/s71/dylancolesss/Logomakr_1JQf3o_1.png" border="0" alt=" photo Logomakr_1JQf3o_1.png" style="width:100%; height:100%;"/>
        </div>
      </div>  
    <br />
    <br />
    
    <div class="row">
          <%= form_for @conn, session_path(@conn, :login), 
      [as: "user", class: "form-inline w-75"], fn f -> %>

      <div class="form-group" style="margin-left: 30%; margin-right: 5%;">
          <input type="text" placeholder="email" class="form-control" name="email">
      </div>

      <div class="form-group">
        <input type="password" placeholder="password" class="form-control" name="password">
      </div>

      <div class="form-group" style="width: 40REM; margin-left: 30%; margin-top: 10%; ">
        <input type="submit" value="Login" class="btn btn-dark"> 
        <span style= "margin-left: 3%;">
          <%= link "Sign Up", to: user_path(@conn, :new), class: "btn btn-warning" %>
        </span>
      </div>
        <% end %>
    </div>
  </div>
   <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>